language: python
install: python bootstrap.py --distribute; ./bin/buildout versions:robotframework=$ROBOTFRAMEWORK_VERSION
python:
   - "2.6"
   - "2.7"
env:
   - ROBOTFRAMEWORK_VERSION=2.9.2
script:
  - ./bin/robotframework --monitorwidth 65 tests/

